### ISSUE TITLE
Ardell-Armour connectivity has neuron population paths ending in blood

### ISSUE THREAD

**Issue by dbrnz** [open-physiology/apinatomy-models#14] opened 2022-08-16 00:23 UTC
The model's SVG shows several neuron population groups ending in the endothelium yet connectivity obtained from SCKAN shows these as ending in blood. Paths 6, 7a, 7v, 8a, 8v, 9a, 9v, 11, and 13.

**Comment by tgbugs** [comment] 2022-08-16 01:11
@MCSZ it looks like we somehow missed fixes on some of A75-A79 when we did the order inversion.

**Comment by tgbugs** [comment] 2022-08-16 01:34
The second half of the issue is that there was a bad id substitution and the open-physiology-viewer code intelligently filled in the values with the information it had, making a number of things appear as blood.

**Comment by tgbugs** [comment] 2022-08-16 01:40
Now resolved in the sheet, will confirm they are correct on next load.

**Comment by tgbugs** [comment] 2022-08-16 22:26
bromo-3 is also affected, it looks like the trachea layers are in the right order but the housingLayers in chains are inverted

**Comment by tgbugs** [comment] 2022-08-18 23:23
Closing this one since it is fixed in the current internal testing pre-release.

**Closed by tgbugs** 2022-08-18 23:23 UTC
